test:
  name: basic-contract-benchmark
  description: "Read assets"
  workers:
    number: 2
  rounds:
  - label: readAsset
    txDuration: 30
    rateControl:
      type: fixed-load
      opts:
        transactionLoad: 2
    workload:
      module: workload/readAsset.js
      arguments:
        assets: 10
        contractId: basic
