test:
  name: cars-contract-benchmark
  description: "Create some cars. Query the cars. Delete the cars."
  workers:
    number: 4
  rounds:
  - label: queryCar
    txDuration: 15
    rateControl:
      type: fixed-rate
      opts:
        tps: 2000
    # rateControl:
    #   type: maximum-rate
    #   opts:
    #     tps: 300
    #     step: 5
    #     sampleInterval: 10
    #     includeFailed: true
    workload:
      module: workload/queryCar.js
      arguments:
        cars: 10
        contractId: cars
monitors:
  transaction:
  - module: logging
    options:
      fred: 1
