test:
  name: records-contract-benchmark
  workers:
    number: 8
  rounds:
  - label: logBeacons
    txDuration: 5
    rateControl:
      type: fixed-rate
      opts:
        tps: 5
    # rateControl:
    #   type: maximum-rate
    #   opts:
    #     tps: 300
    #     step: 5
    #     sampleInterval: 10
    #     includeFailed: true
    workload:
      module: workload/logBeacons.js
      arguments:
        operatorsCount: 2
        flightsPerOperator: 2
        beaconsPerLog: 120
        violationEvery: 1200 # 1 violation every ... beacons
        contractId: abyssarCC # says contractId but it's chaincode name

