test:
  name: records-contract-benchmark
  workers:
    number: 1
  rounds:
  - label: logBeacons
    # txDuration: 30
    txNumber: 1
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    # rateControl:
    #   type: maximum-rate
    #   opts:
    #     tps: 300
    #     step: 5
    #     sampleInterval: 10
    #     includeFailed: true
    workload:
      module: workload/logBeacons.js
      arguments:
        operatorsCount: 1
        flightsPerOperator: 1
        beaconsPerLog: 2
        violationEvery: 1200 # 1 violation every ... beacons
        contractId: abyssarCC # says contractId but it's chaincode name

