test:
  name: records-contract-benchmark
  workers:
    number: 40
  rounds:
  - label: requestPermits
    # txDuration: 30
    txNumber: 2000
    rateControl:
      type: fixed-rate
      opts:
        tps: 500
    # rateControl:
    #   type: maximum-rate
    #   opts:
    #     tps: 300
    #     step: 5
    #     sampleInterval: 10
    #     includeFailed: true
    workload:
      module: workload/requestPermits.js
      arguments:
        operatorsPerWorker: 20
        boundariesPerPermit: 1
        verticesPerBoundary: 1
        facetsPerBoundary: 1
        contractId: abyssarCC # says contractId but it's chaincode name

