test:
  name: records-contract-benchmark
  workers:
    number: 20
  rounds:
  - label: addOperators
    txDuration: 10
    rateControl:
      type: fixed-rate
      opts:
        tps: 300
    # rateControl:
    #   type: maximum-rate
    #   opts:
    #     tps: 300
    #     step: 5
    #     sampleInterval: 10
    #     includeFailed: true
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name

