test:
  name: uav-contract-benchmark
  workers:
    number: 48
  rounds:
  - label: addOperators
    txDuration: 15
    rateControl:
      type: fixed-rate
      opts:
        tps: 2000
    # rateControl:
    #   type: maximum-rate
    #   opts:
    #     tps: 300
    #     step: 5
    #     sampleInterval: 10
    #     includeFailed: true
    workload:
      module: workload/addOperators.js
      arguments:
        operators: 100
        contractId: uav

