test:
  name: records-contract-benchmark
  workers:
    number: 24
  rounds:
  # - label: addOperators-25
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 25
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-50
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 50
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-75
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 75
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-100
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 100
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-125
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 125
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-150
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 150
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-175
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 175
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-200
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 200
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-225
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 225
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-250
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 250
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-275
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 275
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-300
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 300
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-325
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 325
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-350
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 350
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-375
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 375
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-400
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 400
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-425
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 425
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name        
  # - label: addOperators-450
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 450
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-475
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 475
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-500
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 500
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name    
  # - label: addOperators-525
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 525
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-550
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 550
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name
  # - label: addOperators-575
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 575
  #   workload:
  #     module: workload/addOperators.js
  #     arguments:
  #       contractId: abyssarCC # says contractId but it's chaincode name    
  - label: addOperators-600
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 600
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-625
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 625
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-650
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 650
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name    
  - label: addOperators-675
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 675
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-700
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 700
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-725
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 725
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name   
  - label: addOperators-750
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 750
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-775
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 775
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-800
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 800
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name   
  - label: addOperators-825
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 825
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-850
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 850
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-875
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 875
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name   
  - label: addOperators-900
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 900
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-925
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 925
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-950
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 950
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name   
  - label: addOperators-975
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 975
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-1000
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1000
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-1025
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1025
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name   
  - label: addOperators-1050
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1050
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-1075
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1075
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name
  - label: addOperators-1100
    txNumber: 3000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1100
    workload:
      module: workload/addOperators.js
      arguments:
        contractId: abyssarCC # says contractId but it's chaincode name     